### ISSUE TITLE
Figure out how to handle Overloaded Methods

### ISSUE THREAD

**Issue by AaronWB** [hbarton2/cscd350-f24-CodeCain#15]
The Sprint 1 requirements require Overloaded Methods when removed or renamed, for the user to be given a choice of the current overloaded methods to choose for the action.

Time Estimate: 1 Hour

**Comment by AaronWB** [comment]
Spent an 30mins working on allowing overloaded methods and ran into multiple issues that increased the complexity of the system beyond expected. Will need to look closer to find a more efficient way of implementing this feature.

**Comment by colbycrutcher** [comment]
Spent about an hour and a a half working on these issues. Fixed the issue. Tests still work as well.

Time logges: 1 hr 30 min
