### ISSUE TITLE
Add functionality in CLI for tab autocompletion of commands

### ISSUE THREAD

**Issue by rrudolfo** [hbarton2/cscd350-f24-CodeCain#31]
Description: We can quickly finish the command by tabbing when typing in commands. Not for names.
Time Est: 2 - 3 hours 
Extra Comments: An example would be: how you can quickly finish typing in a file name in the normal command line. 
Current Editor: Aaron Williams-Breth

**Comment by AaronWB** [comment]
Finished the autocomplete using swing, might need to redo the CLI so its actually a CLI instead of a java swing GUI and then we can use JLine 2.

Time Logged: 4 Hours
