### ISSUE TITLE
Update GUI with new methods that have been implemented

### ISSUE THREAD

**Issue by rrudolfo** [hbarton2/cscd350-f24-CodeCain#34]
Description: We currently have updated methods that work correctly but the GUI is not updated to handle these methods
    Time Est: 1 - 2 hours
    Extra Comments: We need to stay on top of editing our GUI while we update our methods
    Current Editor:

**Comment by rrudolfo** [comment]
GUI still needs to be updated to account for the new field parameters that take an extra parameter. Other than that GUI seems to be up to date relatively.

**Comment by AaronWB** [comment]
CLI has been updated with the new methods.

Time Logged: 2 Hours
