### ISSUE TITLE
Downsize Hash Maps To One Class

### ISSUE THREAD

**Issue by aoehlerewu** [hbarton2/cscd350-f24-CodeCain#36]
Need to make UMLClass classname to be the key for the Hash Maps while changing the UMLFields and UMLMethods to not use Hash Maps and use array lists instead.

Estimated Time: 3-4 hours

**Comment by AaronWB** [comment]
Finished the redesign of the back-end with only one hash map while the value now is an object that holds all data previously held within the very inefficient use of extra hash maps.
