### ISSUE TITLE
TASK: Basic Visual Arrows Representing Relationships

### ISSUE THREAD

**Issue by AaronWB** [hbarton2/cscd350-f24-CodeCain#50]
Description: Currently there is no visual representation of two classes being linked in the GUI, this needs to be implemented and have different types of relationships represented.
Time Est: 3 hours
Extra Comments:
Current Editor: Benno Foster

**Comment by benFoster1234567** [comment]
Make arrows work, but ran into issues with possibly breaking existing code. Will find a better approach for storing data relating to the positioning of the arrows on the bottom of the boxes

**Comment by benFoster1234567** [comment]
Added lines in JavaFX. Also got add and remove buttons working. Just need the arrows now, and to figure out how to arrange those

**Comment by benFoster1234567** [comment]
having some trouble coming up with a way to get the arrows to not overlap in JavaFX

**Comment by AaronWB** [comment]
Time Logged: 6 Hours along with using Ben Fosters code as a base to jump off of. Got Arrows working with each type defined but need to now make it so each type is clear as they are all arrows instead of arrows and diamonds depending on the type.

**Comment by AaronWB** [comment]
Time Logged: 1 Hour, getting a diamond shape working was more difficult then expected and getting it to be added to the singular polygon shape we are using was annoying to work out at first.
