### ISSUE TITLE
CLI Save Feature Has Custom File Types

### ISSUE THREAD

**Issue by AaronWB** [hbarton2/cscd350-f24-CodeCain#55]
Description: Save feature in the CLI allows custom file types, this makes the save from CLI to GUI not at clean as GUI only accepts .json
Time Est: 30 min
Extra Comments: Switch it to .json only
Current Editor: Colby Crutcher

**Comment by colbycrutcher** [comment]
Fixed it in 10 minutes. Added endswith(.json) to verify file type.
