### ISSUE TITLE
BUG: CLI Rename/Delete Class - No feedback for non-existent classes

### ISSUE THREAD

**Issue by AaronWB** [hbarton2/cscd350-f24-CodeCain#74]
Description: Add a response for cases where the specified class does not exist.
Time Est: 20mins
Extra Comments: Its handled in the backend methods but not the actual CLI.
Current Editor: Aaron Oehler

**Comment by aoehlerewu** [comment]
I spent 20 mins on this issue on adding feedback when a specified class doesn't exist.
