### ISSUE TITLE
BUG: CLI Field Commands - No Feedback on Errors

### ISSUE THREAD

**Issue by AaronWB** [hbarton2/cscd350-f24-CodeCain#76]
Description: User needs feedback in the CLI when a field docent exist or is a duplicate.
Time Est: 20mins
Extra Comments: None
Current Editor: Aaron Oehler

**Comment by aoehlerewu** [comment]
I spent 20 mins on this issue on adding feedback when a specified field doesn't exist or is a duplicate.
