### ISSUE TITLE
TASK: CLI - Need a List Class Command

### ISSUE THREAD

**Issue by AaronWB** [hbarton2/cscd350-f24-CodeCain#77]
Description: Need a command that when called and specified to a class will give out all the information about that class and what it is connected to through relationships.
Time Est: 20mins
Extra Comments: Just search the hashmap to get the specific ClassInfo Object, and then search through the relationship array.
Current Editor: Aaron Oehler

**Comment by aoehlerewu** [comment]
I spent 20 mins on this issue on adding 'list detail' command that allows the user to see info about a class that included (fields, methods and relationships).
