### ISSUE TITLE
TASK/BUG: CLI Method Command - User Feedback and Overloading Quirks

### ISSUE THREAD

**Issue by AaronWB** [hbarton2/cscd350-f24-CodeCain#78]
Description: User needs to know when they are initializing a method creation if they need comma's or not to list out their parameters. Renaming a method to another method of the same name does not work, but should work but not to a method of the same name and parameters.
Time Est: 1 Hour
Extra Comments: None
Current Editor: Aaron Oehler

**Comment by colbycrutcher** [comment]
Finished it in 1 hour and 30 min
