### ISSUE TITLE
TASK: Export UML GUI As a PNG/JPEG - From GUI

### ISSUE THREAD

**Issue by AaronWB** [hbarton2/cscd350-f24-CodeCain#81]
Description: The user wants a feature of pressing a button in GUI to take a snapshot of the whole current UML Diagram
Time Est: 2 Hours
Extra Comments: Make it so its readable.
Current Editor: Sergei

**Comment by SergeiAshikhmin** [comment]
Time log: 2 hours.
I researched the implementation of a feature. Users can export the diagram as a PNG image now.

**Comment by AaronWB** [comment]
Time Log: 40 Minutes.
Feature enhancement where the snapshot is dedicated by the bounds of the classnodes so there is no wasted space when exporting.
