### ISSUE TITLE
TASK: 90% of Code Coverage For Model Portion of the Code

### ISSUE THREAD

**Issue by AaronWB** [hbarton2/cscd350-f24-CodeCain#83]
Description: Project Manager requires at least 90% of our model code is tested.
Time Est: 1 Hour
Extra Comments: Make it well documented and if needed go back and refactor old tests and include them.
Current Editor: Riley Rudolfo

**Comment by rrudolfo** [comment]
How Far I Got: I got the relationships code coverage from 58% to 94%. However I had to change some code to the relationship class to handle edge cases. 
Time Spent: About 2 and 1/2 hours
Currently Working On: Save Manager

**Comment by rrudolfo** [comment]
How far I got: I got the relationship type code coverage from 0% to 97%. Now, the total code coverage is 73%. 
Time spent: 1.5 hours
Currently Working On: Save Manager and UMLClass classes to improve their code coverage.

**Comment by rrudolfo** [comment]
How far I got: I have got the save manager class to 97% code coverage putting up the total code coverage to 82%. 
Time spent: 1.5 hours
Currently Working on: UMLClass and UMLMethodsInfo and UMLMethods code coverage

**Comment by rrudolfo** [comment]
I have completed the test files to get to 92% code coverage and created the pull request for it.
