### ISSUE TITLE
TASK: GUI Arrows Need to Not Overlap AT ALL

### ISSUE THREAD

**Issue by AaronWB** [hbarton2/cscd350-f24-CodeCain#85]
Description: Whenever a relationship is added, or a classbox is moved around, the arrows need to be in constant updating to never cross over each other no matter what.
Time Est: 5 Hours
Extra Comments: With the classbox algorithm in place there will be less possible breakage first.
Current Editor: Benno Foster

**Comment by benFoster1234567** [comment]
I made a few classes. Had to go to bed though, So I just made a new branch to save my progress. Only thing missing is how to find the screen size, or the size of the pane containing the nodes I think. I made a method to print the changes to the console, but it's not printing anytinhg, so I think I may have used the wrong method to find the size of the pane. I'll be on tomorrow after work probably but if anyone wants to try and expand on it feel free to

**Comment by benFoster1234567** [comment]
Arrow lines no longer overlap
